
version: '3'
services:
    app:
        image: php:8.1-fpm
        ports:
            - "3000:3000"
        restart: always
        working_dir: /var/www/html
        command: php -S 0.0.0.0:3000
        volumes:
            - ./:/var/www/html


